### ISSUE TITLE
User emulation

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#102]
It would help a lot if we could 'log in' as another user, i.e. emulate a given SU username (instead of switching between roles). Then the role could be derived from our logic, and we would be able to test things a lot more thoroughly. Right now it's very hard to replicate the issues reported by users, and it has been great pain in mediasite as well.

**Comment by booski** [comment]
This is kind of tricky since we don't store user info - there's no immediate way to know what entitlements another user would show up with.

A possible solution would be to query the info from SUKAT when impersonating. SUKAT exposes all entitlements for all users, so we could build a "fake" set of entitlements from there based on the person to impersonate.

**Comment by orkit** [comment]
Implemented!
