### ISSUE TITLE
Misc download issues

### ISSUE THREAD

**Issue by booski** [dsv-su/play#111]
There are a number of issues with the download function that need fixing:

 - The platform saves both a zip and the raw files for each downloadable presentation, using twice the necessary space. Only the zip should be kept.
 - The files to be zipped should be stored in a true temporary location (such as /tmp), not next to the zip to be produced.
 - Some zip packages don't include the player, possibly due to being a single stream. This is inconsistent with no upside. If the platform is to distinguish between single and multiple streams, single streams should be downloaded directly as mp4:s with no zipping. The other option would be to treat all presentations the same no matter the number of streams.
 - There is no feedback, either when waiting for a zip to be created or downloaded.
 - There are places where the download button exists but doesn't seem to work, see "DSHI Föreläsning 1" on the dev start page.
 
In the long run all zip handling should be moved to the storage server, but that is a bigger job tracked as a separate issue #110

**Comment by orkit** [comment]
- We can delete the raw files that are download directly and delete the zip file every night to save storage space. We can also change the storage path to a  /tmp folder.

- All presentations are treated the same way no matter the number of streams. The zip file contains the player with the video and the poster files. If there is a presentation without the player, then something is wrong and then we have to look at the current presentation.

- There should be feedback in the form of a popup spinner when the files are downloaded from the play store and prepared. When the zip file is then downloaded, the browser's popup is used.

- The places were the download button exist but doesn't download seems to be fixed in the latest update.

**Comment by orkit** [comment]
The zip download has been refactored and now the above problems should be fixed.
