### ISSUE TITLE
Improving suggestions when searching for users

### ISSUE THREAD

**Issue by booski** [dsv-su/play#113]
The current user suggestion function takes the entire string entered and runs an ldap query matching on the cn (common name, first + last name). This has a few undesirable side effects, for example a user with a middle name in SUKAT will not be found when searching for them by first + last name:

Name in sukat: Anders Bengt Carlsson
 - Searching for "Anders" will match but there are a lot of them
 - Searching for "Anders Ca" will not match, due to the middle name getting in the way
 - "Carlsson" will not match due to the search only matching from the start of the name

A solution to this would be to do individual searches per entered word, and looking at more than just the cn attribute:

Search string: "ande ca"
 - Split the string on (possibly multiple consecutive) spaces, resulting in "ande" and "ca"
 - Construct an ldap query looking at 'sn' and 'givenName' for each of the strings:
```
(&             #require both sub-queries to match
  (|           #accept as match if any of the sub-queries match
    (givenName=ande*)
    (sn=ande*)
    (uid=ande*)
  )
  (|           #accept as match if any of the sub-queries match
    (givenName=ca*)
    (sn=ca*)
    (uid=ca*)
  )
)
```

Pseudo-code:
```php
$searchterms = preg_split('/\s+/', $inputstring);
$search = '(&';
foreach($searchterms as $term) {
  $search .= "(|(givenName=$term*)(sn=$term*)(uid=$term*))";
}
$search .= ')';
//apply the search to some ldap connection... 
```
Doing this would make the search for "ande ca" return all users matching both words in either their first, last or usernames.

**Comment by booski** [comment]
Closely related to #98

**Comment by pavelsokolov** [comment]
There's a problem with people with multiple first/last names.

Example: Ann Maria Dorotea Bergholtz
Sukat firstname: Ann Maria Dorotea
Sukat lastname: Bergholtz

Right now a search for Ma* Berg* doesn't find her because the sukat first name starts with 'Ann' and not 'Maria'. To be able to find her, we would need to perform a full substring search (sn=*$term*) instead of (sn=$term*). But this search is quite expensive.

Also it's not possible to find her via 'Ann Maria' because then the search expects both keywords to be present in either of the names. 

I tend to think that this could be an exception that we can live with, since 99% of users should have 'valid' names.

**Comment by pavelsokolov** [comment]
There's a problem with people with multiple first/last names.

Example: Ann Maria Dorotea Bergholtz
Sukat firstname: Ann Maria Dorotea
Sukat lastname: Bergholtz

Right now a search for Ma* Berg* doesn't find her because the sukat first name starts with 'Ann' and not 'Maria'. To be able to find her, we would need to perform a full substring search (sn=*$term) instead of (sn=$term*). But this search is quite expensive.

Also it's not possible to find her via 'Ann Maria' because then the search expects both keywords to be present in either of the names.

I tend to think that this could be an exception that we can live with, since 99% of users should have 'valid' names.
