### ISSUE TITLE
Manual upload video media

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#15]
Add validation for uploaded mediafiles:
- The uploaded mediafiles should be of a format that can be played by the multiplayer.
- The secondary mediafiles duration should not exceed the primary mediafile.

**Comment by booski** [comment]
Mediafile format should not be a problem, since the storage server should detect videos with the "wrong" encoding and automatically re-encode them. 
If it is possible without having the entire file, it may be useful to validate that ffmpeg can handle the format. That way the user doesn't have to wait through an entire upload just to be informed that the format is unsupported.

Secondary media duration should probably be required to be within a few seconds of the primary. Diffs could be acceptable in both directions (longer/shorter), as long as they stay below 3 seconds or so. Any major discrepancies in video length would cause confusion regarding synchronization that should really be avoided.

It should be fairly trivial to change the relevant logic to use the longest clip in a bundle as the duration instead of the primary, but for the moment we'll live with potentially cutting a few seconds on a secondary stream.

**Comment by orkit** [comment]
Validation of the video mediaformats takes place in the backend towards a validation format list. The list is (should) be formats that ffmeg can handle. The following formats can be uploaded: mp4, mov, avi, webm, mpg, mpeg, wmv, qt, avchd.

The duration of each file is checked against the primary videofile (can later be changed to the longest uploaded file if necessary) and the files must not differ more than +/-3 seconds (from the primaryfile) to pass the validation.
