### ISSUE TITLE
Finalize the header/footer

### ISSUE THREAD

**Issue by booski** [dsv-su/play#4]
All placeholders should be removed.
The header should contain these items:
 - Catalogue (always)
 - My videos (if a user owns any videos)
These items should merge into a hamburger menu only on small screens, otherwise there should be no hamburger at all.
There should be some indication of who a user is logged in as in the header. Username and/or fullname.
The search bar should always be visible.

**Comment by orkit** [comment]
I have added two small buttons to the header. They are only there during development and should be removed before production. One shows the status of the demon on play-store and the other shows the total number of presentations stored in the platform. Pressing the presentations button retrieves and updates all presentations from the play-store (reloads to original state).

I have bound the variables, $courses and $hasmycourses to render for all views because they are needed in the header. If more variables need to be bound to all views, this can be done in the class App\Services\Header\CourseNav.php

**Comment by booski** [comment]
I like those indicators. I agree that they shouldn't be in that position in production, but the admin page might benefit from showing that information, so I suggest finding a permanent place for those two data points on the admin page.

**Comment by booski** [comment]
This seems finished, so closing.
